version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/faqdb
      - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data:
